# Don't allow users to create custom issues
blank_issues_enabled: true

# Additional contact links
contact_links:
  - name: Kerig Support
    url: https://support.kerig.ee
    about: You can get support here.
